## Упражнение № 1

Создайте Series из каждого из элементов: списка, ndarray и словаря.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [10]:
import numpy as np
import pandas as pd

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## Упражнение № 2

Преобразуйте `ser` в датафрейм с его индексом в качестве еще одного столбца датафрейма.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
```

In [15]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.reset_index()
df.columns = ['index', 'value']
print(df)


   index  value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


## Упражнение № 3

Объедините `ser1` и `ser2`, чтобы сформировать датафрейм.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```


In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(list(mydict.keys()))
ser2 = pd.Series(list(mydict.values()))

df = pd.DataFrame({'Column1': ser1, 'Column2': ser2})
print(df)


   Column1  Column2
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


## Упражнение № 4

Добавьте имя ряда  `ser`, назвав его `latin_letters`.

Пример входных данных:

```python
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
```

In [17]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'latin_letters'
print(ser)


0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


## Упражнение № 5

Из `ser1` удалите элементы, присутствующие в `ser2`.

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [18]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

result = ser1[~ser1.isin(ser2)]
print(result)


0    1
1    2
2    3
dtype: int64


## Упражнение № 6

Получить все элементы `ser1` и `ser2`, которые не являются общими для обоих рядов.

Пример входных данных:

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [19]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

result = pd.concat([ser1[~ser1.isin(ser2)], ser2[~ser2.isin(ser1)]])
print(result)


0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


## Упражнение № 7

Вычислите минимальное значение, 25-й процентиль, медиану, 75-й процентиль и максимальное значение `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.normal(10, 5, 25))
```

In [20]:
ser = pd.Series(np.random.normal(10, 5, 25))

statistics = {
    "min": ser.min(),
    "25%": ser.quantile(0.25),
    "median": ser.median(),
    "75%": ser.quantile(0.75),
    "max": ser.max(),
}

print(statistics)


{'min': np.float64(-5.241086891297826), '25%': np.float64(7.4557769523683985), 'median': np.float64(10.371139230888538), '75%': np.float64(14.139366084695457), 'max': np.float64(18.227593451218677)}


## Упражнение № 8

Вычислите частоту встречаемости каждого уникального значения `ser`.

Пример входных данных:

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [21]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

frequency = ser.value_counts()
print(frequency)


h    7
e    5
a    4
g    4
d    4
b    3
c    2
f    1
Name: count, dtype: int64


## Упражнение № 9

Из `ser` оставить 2 наиболее часто встречающихся элемента без изменений, а все остальные заменить на `Прочее`.

Пример входных данных:

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [26]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

top_two = ser.value_counts().index[:2]
ser[~ser.isin(top_two)] = 'Прочее'
print(ser)

0          4
1          2
2     Прочее
3     Прочее
4          4
5          4
6          4
7     Прочее
8     Прочее
9          2
10         2
11    Прочее
dtype: object


C:\Users\lewac\AppData\Local\Temp\ipykernel_18536\3962796178.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Прочее' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(top_two)] = 'Прочее'


## Упражнение № 10

Разбейте ряд `ser` на 10 равных децилей и замените значения на название дециля.

Пример входных данных:

```python
ser = pd.Series(np.random.random(20))
```

Пример выходных данных:

```python
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```


In [27]:
ser = pd.Series(np.random.random(20))

labels = ['{}th'.format(i) for i in range(1, 11)]
ser_bins = pd.qcut(ser, 10, labels=labels)

print(ser_bins)


0      3th
1      5th
2      3th
3      1th
4      2th
5      8th
6      4th
7     10th
8      4th
9      6th
10     2th
11    10th
12     7th
13     1th
14     6th
15     7th
16     9th
17     8th
18     5th
19     9th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']


## Упражнение № 11

Переформируйте ряд `ser` в датафрейм с 7 строками и 5 столбцами

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [28]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = ser.values.reshape(7, 5)
print(pd.DataFrame(df))


   0  1  2  3  4
0  4  3  5  7  3
1  8  4  8  5  9
2  5  2  5  3  7
3  8  1  3  2  7
4  2  4  5  7  7
5  3  2  6  1  2
6  1  9  4  5  1


## Упражнение № 12

Найти позиции чисел, кратных 3, из ряда `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 7))
```

In [31]:
ser = pd.Series(np.random.randint(1, 10, 7))
positions = ser[ser % 3 == 0].index.tolist()
print(positions)


[2, 3, 5]


## Упражнение № 13

Из `ser` извлечь элементы, находящиеся на позициях в списке `pos`.

Пример входных данных:

```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
```


In [32]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

result = ser.iloc[pos]
print(result)


0     a
4     e
8     i
14    o
20    u
dtype: object


## Упражнение № 14

Объедините `ser1` и `ser2` по вертикали и горизонтали (чтобы сформировать датафрейм).

Пример входных данных:

```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [33]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

df_horizontal = pd.concat([ser1, ser2], axis=1)
df_vertical = pd.concat([ser1, ser2], axis=0)

print("Horizontal:")
print(df_horizontal)
print("Vertical:")
print(df_vertical)

Horizontal:
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
Vertical:
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


## Упражнение № 15

Получите позиции элементов `ser2` в `ser1` в виде списка.

Пример входных данных:

```python
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
```

In [34]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

positions = [ser1[ser1 == value].index[0] for value in ser2]
print(positions)


[np.int64(5), np.int64(4), np.int64(0), np.int64(8)]


## Упражнение № 16

Вычислить среднеквадратическую ошибку рядов `truth` и `pred`.

Пример входных данных:

```python
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
```

In [35]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

mse = ((truth - pred) ** 2).mean()
print(mse)

0.4322869950466016


## Упражнение № 17

В каждом слове `ser` поставьте первый символ каждого слова в верхний регистр.

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [36]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
capitalized = ser.str.capitalize()
print(capitalized)


0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18

В каждом слове `ser` посчитайте число символов.

Пример входных данных:

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [37]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
lengths = ser.str.len()
print(lengths)

0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

Вычислите разность разностей между последовательно идущими числами в `ser`.

Пример входных данных:

```python
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
```

Пример выходных данных:

```
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
```


In [38]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

first_diff = ser.diff()
second_diff = first_diff.diff()

print(first_diff)
print(second_diff)

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


## Упражнение № 20

Преобразуйте строковое представление дат в `datetime64`.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [42]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

formats = ['%d %b %Y', '%d-%m-%Y', '%Y%m%d', '%Y/%m/%d', '%Y-%m-%d', '%Y-%m-%dT%H:%M']

datetime_ser = ser.apply(
    lambda x: pd.to_datetime(x, errors='coerce', format=None)
)
print(datetime_ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [49]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

dates = pd.to_datetime(ser, format='mixed')
day_of_month = dates.dt.day
week_number = dates.dt.isocalendar().week
day_of_year = dates.dt.dayofyear
day_of_week = dates.dt.day_name()

print("Date:", day_of_month.tolist())
print("Week number:", week_number.tolist())
print("Day num of year:", day_of_year.tolist())
print("Day of week:", day_of_week.tolist())

Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day num of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## Упражнение № 22

Замените элементы `ser` на даты, начинающиеся с 4-го числа соответствующего месяца.

Пример входных данных:

```python
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
```

Пример выходных данных:

```
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]
```

In [4]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser = pd.to_datetime(ser) + pd.offsets.Day(3)
print(ser)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


C:\Users\lewac\AppData\Local\Temp\ipykernel_3140\840979140.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ser = pd.to_datetime(ser) + pd.offsets.Day(3)


## Упражнение № 23

Из `ser` извлеките слова, содержащие не менее 2 гласных букв.

Пример входных данных:

```python
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Пример выходных данных:

```
0     Apple
1    Orange
4     Money
dtype: object
```


In [6]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
vowels = "aeiouAEIOU"
filtered = ser[ser.str.count(f"[{vowels}]") >= 2]
print(filtered)

0     Apple
1    Orange
4     Money
dtype: object


## Упражнение № 24

Извлеките корректные адреса электронной почты из ряда `emails`. Шаблон регулярного выражения для корректных адресов электронной почты приведен в качестве образца.

Пример входных данных:

```python
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
```

Пример выходных данных:

```
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
```

In [7]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'
valid_emails = emails[emails.str.contains(pattern, regex=True)]
print(valid_emails)

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
C:\Users\lewac\AppData\Local\Temp\ipykernel_3140\1539219037.py:2: SyntaxWarning: invalid escape sequence '\.'
  pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'


## Упражнение № 25

Вычислить среднее значение веса в `weights` для каждого фрукта из `fruit`.

Пример входных данных:

```python
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
```

Пример выходных данных:

```python
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64
```

In [9]:
import numpy as np

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
mean_weights = weights.groupby(fruit).mean()
print(mean_weights)


apple     2.000000
banana    8.000000
carrot    3.666667
dtype: float64


## Упражнение № 26

Вычислить [евклидово расстояние](https://en.wikipedia.org/wiki/Euclidean_distance) между векторами $p$ и $q$, не используя встроенную формулу.

Пример входных данных:

```python
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
```

Пример выходных данных:

```
18.165
```

In [11]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
distance = np.sqrt(((p - q) ** 2).sum())
print(distance)

18.16590212458495


## Упражнение № 27

Получите позиции пиков (значений, окруженных с двух сторон меньшими значениями) в `ser`.

Пример входных данных:

```python
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
```

Пример выходных данных:

```
array([1, 5, 7])
```

In [12]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
peaks = np.where((ser > ser.shift(1)) & (ser > ser.shift(-1)))[0]
print(peaks)


[1 5 7]


## Упражнение № 28

Замените пробелы в `my_str` на наименее часто встречающийся символ.

Пример входных данных:

```python
my_str = 'dbc deb abed gade'
```

Пример выходных данных:

```
'dbccdebcabedcgade'  # least frequent is 'c'
```

In [13]:
from collections import Counter

my_str = 'dbc deb abed gade'
freq = Counter(my_str.replace(' ', ''))
char = freq.most_common()[-1][0]
result = my_str.replace(' ', char)
print(result)

dbcgdebgabedggade


## Упражнение № 29

Создайте временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа

Пример выходных данных:

```
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6
```

In [14]:
dates = pd.date_range(start='2000-01-01', periods=10, freq='7D')
random_values = np.random.randint(1, 10, size=10)
time_series = pd.Series(random_values, index=dates)
print(time_series)

2000-01-01    2
2000-01-08    1
2000-01-15    7
2000-01-22    5
2000-01-29    6
2000-02-05    5
2000-02-12    7
2000-02-19    7
2000-02-26    3
2000-03-04    3
Freq: 7D, dtype: int32


## Упражнение № 30

В `ser` отсутствуют некоторые даты и значения. Сделайте так, чтобы все отсутствующие даты появились и заполнились значением из предыдущей даты.

Пример входных данных:

```python
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64
```

Пример выходных данных:

```
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
```

In [15]:
ser = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser = ser.reindex(pd.date_range(start=ser.index.min(), end=ser.index.max(), freq='D')).fillna(method='ffill')
print(ser)

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64


C:\Users\lewac\AppData\Local\Temp\ipykernel_3140\4215555315.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser = ser.reindex(pd.date_range(start=ser.index.min(), end=ser.index.max(), freq='D')).fillna(method='ffill')


## Упражнение № 31

Вычислите автокорреляции для первых 10 лагов `ser`. Определите, какой из лагов имеет наибольшую корреляцию. (см. также [Модель авторегрессии и распределённого лага — Википедия](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B8_%D0%B8_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BB%D0%B0%D0%B3%D0%B0))

Пример входных данных:

```python
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
```

Пример выходных данных:

```
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [19]:
ac = [ser.autocorr(lag) for lag in range(1, 11)]
max_lag = np.argmax(ac) + 1
print(ac)
print("Lag having highest correlation:", max_lag)

[np.float64(0.3936465655286895), np.float64(-0.4344738780433504), np.float64(-1.0), np.float64(-0.5773502691896257), np.float64(nan), np.float64(nan), np.float64(nan), nan, nan, nan]
Lag having highest correlation: 5


## Упражнение № 32

Импортируйте каждую 50-ю строку набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', skiprows=lambda x: x % 50 != 0)
print(df)

      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5  0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6  0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7  9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8  7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9  0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   

        b  lstat  medv  
0  396.90  16.20  19.4  
1  396.90   6.19  33.2  
2  351.85  21.45  15.4  
3  396.90   4.56  34.9  
4  393.74   6.56

## Упражнение № 33

Импортируйте набор данных [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), но при импорте измените столбец `'medv'` (*median house value*) так, чтобы значения < 25 стали `Low`, а > 25 - `High`.


In [21]:
df['medv'] = df['medv'].apply(lambda x: 'Low' if x < 25 else 'High')
print(df.head())

      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   

        b  lstat  medv  
0  396.90  16.20   Low  
1  396.90   6.19  High  
2  351.85  21.45   Low  
3  396.90   4.56  High  
4  393.74   6.56  High  


## Упражнение № 34

Создайте датафрейм со строками в виде шагов (интервалов) заданного ряда

Пример входных данных:

```python
L = pd.Series(range(15))
```

Пример выходных данных:

```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```


In [35]:
L = pd.Series(range(15))

n = 4
result = np.array([L[i:i + n].values for i in range(len(L) - n + 1)])

print(result)

[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## Упражнение № 35

Импортируйте столбцы 'crim' и 'medv' из набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df)

        crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]


## Упражнение № 36

Получите количество строк, столбцов, тип данных и суммарную статистику каждого столбца набора данных [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv). Также получите эквивалент датафрейма в виде numpy-массива и списка.


In [25]:
print("Количество строк и столбцов:", df.shape)
print("Типы данных:", df.dtypes)
print("Суммарная статистика:", df.describe())
print("Numpy массив:", df.to_numpy())
print("Список:", df.values.tolist())

Количество строк и столбцов: (506, 2)
Типы данных: crim    float64
medv    float64
dtype: object
Суммарная статистика:              crim        medv
count  506.000000  506.000000
mean     3.613524   22.532806
std      8.601545    9.197104
min      0.006320    5.000000
25%      0.082045   17.025000
50%      0.256510   21.200000
75%      3.677083   25.000000
max     88.976200   50.000000
Numpy массив: [[6.3200e-03 2.4000e+01]
 [2.7310e-02 2.1600e+01]
 [2.7290e-02 3.4700e+01]
 ...
 [6.0760e-02 2.3900e+01]
 [1.0959e-01 2.2000e+01]
 [4.7410e-02 1.1900e+01]]
Список: [[0.00632, 24.0], [0.02731, 21.6], [0.02729, 34.7], [0.03237, 33.4], [0.06905, 36.2], [0.02985, 28.7], [0.08829, 22.9], [0.14455, 27.1], [0.21124, 16.5], [0.17004, 18.9], [0.22489, 15.0], [0.11747, 18.9], [0.09378, 21.7], [0.62976, 20.4], [0.63796, 18.2], [0.62739, 19.9], [1.05393, 23.1], [0.7842, 17.5], [0.80271, 20.2], [0.7258, 18.2], [1.25179, 13.6], [0.85204, 19.6], [1.23247, 15.2], [0.98843, 14.5], [0.75026, 15.6], [0.84054,

## Упражнение № 37

Извлеките номер строки и столбца конкретной ячейки по заданному критерию.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

max_price_idx = df['Price'].idxmax()
manufacturer, model, car_type = df.loc[max_price_idx, ['Manufacturer', 'Model', 'Type']]
print(f"Производитель: {manufacturer}, Модель: {model}, Тип: {car_type}")

row_number = max_price_idx
col_number = df.columns.get_loc('Price')
print(f"Номер строки: {row_number}, Номер столбца: {col_number}")

Производитель: Mercedes-Benz, Модель: 300E, Тип: Midsize
Номер строки: 58, Номер столбца: 4


## Упражнение № 38

Переименуйте в `df` столбец `Type` в `CarType` и замените `.` в именах столбцов на `_`.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

Пример выходных данных:

```python
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.rename(columns={'Type': 'CarType'}, inplace=True)
df.columns = df.columns.str.replace('.', '_')
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

Проверьте, нет ли в `df` отсутствующих значений.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [39]:
missing = df.isnull().any().any()
print("Пропущенные значения:", missing)

Пропущенные значения: True


## Упражнение № 40

Подсчитайте количество пропущенных значений в каждом столбце `df`. Какой столбец имеет наибольшее число пропущенных значений?

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [40]:
missing_counts = df.isnull().sum()
max_missing_col = missing_counts.idxmax()
print("Пропущенные значения по столбцам:\n", missing_counts)
print("Столбец с наибольшим количеством пропущенных значений:", max_missing_col)

Пропущенные значения по столбцам:
 Manufacturer           4
Model                  1
CarType                3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64
Столбец с наибольшим количеством пропущенных значений: AirBags


## Упражнение № 41

Замените отсутствующие значения в столбцах `Min.Price` и `Max.Price` на соответствующие им средние значения.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```